name: CI/CD Pipeline with Docker

on: 
  - push
  - pull_request

jobs:
  test-runner:
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Print System Info
        run: uname -a

      - name: List Files
        run: ls -alh

  docker-deployment:
    runs-on: self-hosted
    needs: test-runner  # Ensures Docker deployment starts only after the test job completes
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Start Docker Container
        run: |
          sudo docker run -d \
            --name my-container \
            -p 8080:80 \
            nginx:latest

      - name: Verify Container Running
        run: docker ps

      - name: Wait for Container (Optional)
        run: sleep 5  # Ensures the container is fully started before testing

      - name: Test Access to Container
        run: curl http://localhost:8080
